Insert into candidato (nombre_candidato) values ("Monkey D. Luffy");
Insert into candidato (nombre_candidato) values ("Edward Elric");
Insert into candidato (nombre_candidato) values ("Vinsmoke Sanji");
Insert into candidato (nombre_candidato) values ("Roronoa Zoro");
Insert into candidato (nombre_candidato) values ("Spike Spiegel");
Insert into candidato (nombre_candidato) values ("Arsene Lupin III");
Insert into candidato (nombre_candidato) values ("Lelouch Lamperouge");
Insert into candidato (nombre_candidato) values ("Vssh Estampida");
Insert into candidato (nombre_candidato) values ("Nagisa Furukawa");
Insert into candidato (nombre_candidato) values ("Chii");
Insert into candidato (nombre_candidato) values ("Himura Kenshin");
Insert into candidato (nombre_candidato) values ("Adashino Benio");
Insert into candidato (nombre_candidato) values ("Kobayashi Tohru");
Insert into candidato (nombre_candidato) values ("Meiko Honma");
Insert into candidato (nombre_candidato) values ("Tachibana Kanade");
Insert into candidato (nombre_candidato) values ("Emiya Hirou");